all:
	mkdir -p resources/home/dnanexus/selphi/modules
	cp ../../selphi.py resources/home/dnanexus/selphi/
	cp ../../pyproject.toml resources/home/dnanexus/selphi/
	cp ../../requirements.txt resources/home/dnanexus/selphi/
	cp ../../modules/*.py resources/home/dnanexus/selphi/modules/

clean:
	rm -rf resources/home
